"""added null support

Revision ID: 211c8c3bd43c
Revises: 0021e4cb0efb
Create Date: 2026-03-25 01:52:24.752358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211c8c3bd43c'
down_revision: Union[str, Sequence[str], None] = '0021e4cb0efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profile', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profile', 'avatar_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profile', 'bio',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'bio',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profile', 'avatar_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profile', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profile', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
